src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>GitHub_Handle__c</fullName>
        <label>GitHub Handle</label>
        <length>32</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>CI_Project_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CI Project Definition</label>
        <referenceTo>ProjectDefinition__c</referenceTo>
        <relationshipLabel>Environments</relationshipLabel>
        <relationshipName>Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Namespace__c</fullName>
        <label>Namespace</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Packaging__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Packaging?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Environment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose an Enviroment that is a member of the same Project Definition</errorMessage>
            <filterItems>
                <field>Environment__c.CI_Project_Definition__c</field>
                <operation>equals</operation>
                <valueField>$Source.CI_Project_Definition__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Environments</relationshipLabel>
        <relationshipName>Child_Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Production</label>
        <type>Checkbox</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OAuth_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>GitHub OAuth Settings</description>
    <fields>
        <fullName>Redirect_Url__c</fullName>
        <label>Redirect Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Github OAuth Settings</label>
</CustomObject>

src/objects/ProjectDefinition__c.object
<CustomObject>
    <description>Container for Praying Mantis CI definition</description>
    <fields>
        <fullName>Namespace__c</fullName>
        <label>Namespace</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Package_Name__c</fullName>
        <label>Package Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repo_Name__c</fullName>
        <label>Repository Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Repo_Url__c</fullName>
        <label>Repository URL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CI Project Definition</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CI Project Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Team_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Memberships</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Handle__c</fullName>
        <label>GitHub Handle</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Definition__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Project Definition</label>
        <referenceTo>ProjectDefinition__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UserDefinition__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>CI_Token__c</fullName>
        <label>CI Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VCS_Token__c</fullName>
        <label>VCS Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CI User Definition</label>
</CustomObject>

src/classes/TestFactory.cls
@isTest
public class TestFactory {
	
	// User
	public static User factoryUser(Boolean dml, String profileName){
		Profile p = [SELECT Id FROM Profile WHERE Name=:profileName];
		Integer userkey = Math.round(Math.random()*1000);
		String userNameString = 'user.'+userKey+'@testorg.com';
		System.debug('USERNAME: '+userNameString);
        User u = new User(Alias = 'standt', Email=userNameString, 
            EmailEncodingKey='UTF-8', FirstName='Test', LastName=profileName, LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName=userNameString);
        if(dml){
			insert u;
		}
		return u;
	}

	// oAuth Settings
	public static OAuth_Settings__c factoryOauthSetting(Boolean dml){
		OAuth_Settings__c oauth = OAuth_Settings__c.getOrgDefaults();
		oauth.Redirect_Url__c = 'codescience.com';
		if(dml){
			upsert oauth;
		}
		return oauth;
	}

	// User Settings
	public static UserDefinition__c factoryUserDefinition(Boolean dml){
		UserDefinition__c uds = UserDefinition__c.getInstance(UserInfo.getUserId());
		uds.VCS_Token__c = '1234567890';
		uds.CI_Token__c = '0987654321';
		if(dml){
			upsert uds;
		}
		return uds;
	}

	// Project Definition
	public static ProjectDefinition__c factoryProjectDefinition(Boolean dml){
		ProjectDefinition__c projectDef = new ProjectDefinition__c();
		projectDef.Name = 'Test Project';
		projectDef.Namespace__c = 'testnamespace';
		projectDef.Package_Name__c = 'testpackage';
		projectDef.Repo_Name__c = 'CodeScience/Test-Project';
		projectDef.Repo_Url__c = 'https://github.com/CodeScience/Test-Project';
		if(dml){
			upsert projectDef;
		}
		return projectDef;
	}

	// Team Members
	public static List<Team_Member__c> factoryTeamMembers(Boolean dml, ProjectDefinition__c projectDef, Integer count){
		List<Team_Member__c> members = new List<Team_Member__c>();
		String name = 'Test Member';
		String github = 'github';
		for(Integer i=1; i<=count; i++){
			members.add(factoryTeamMember(false, projectDef, null, name+i, github+i));
		}
		if(dml){
			upsert members;
		}
		return members;
	}
	public static Team_Member__c factoryTeamMember(Boolean dml, ProjectDefinition__c projectDef, Contact contact, String name, String github){
		Team_Member__c member = new Team_Member__c();
        if(contact == null){
        	contact = factoryContact(true,null,null);
        }
        member.Project_Definition__c = projectDef.Id;
        member.Contact__c = contact.Id;
        // Name manager
        List<String> nameList = nameGenerator(name);
        member.Name = nameList.get(0);
        member.First_Name__c = nameList.get(1);
        member.Last_Name__c = nameList.get(2);
		// GitHub Handle manager
        if(String.isBlank(github)){
			member.Github_Handle__c = 'github';
		}
		else {
			member.Github_Handle__c = github;
		}
		// DML
		if(dml){
			upsert member;
		}
        return member;
	}

	// Environment
	public static Environment__c factoryEnvironment(Boolean dml, ProjectDefinition__c projectDef, Environment__c parentEnv ,String name, String namespace, Boolean production, Boolean packaging){
		Environment__c env = new Environment__c();
		if(projectDef == null){
			projectDef = factoryProjectDefinition(true);
		}
		env.Name = name;
		env.CI_Project_Definition__c = projectDef.Id;
		env.Namespace__c = namespace;
		env.Packaging__c = packaging;
		env.Parent_Environment__c = parentEnv == null ? null : parentEnv.Id;
		env.Production__c = production;
		// DML
		if(dml){
			upsert env;
		}
        return env;
	}

	// Account
	public static Account factoryAccount(Boolean dml){
		Account account = new Account();
		account.Name = 'Test Account';
		if(dml){
			upsert account;
		}
        return account;
	}

	// Contact
	public static List<Contact> factoryContacts(Boolean dml, Account account, Integer count){
		List<Contact> contacts = new List<Contact>();
		String name = 'Test Contact';
		for(Integer i=1; i<=count; i++){
			contacts.add(factoryContact(false, account, name+i));
		}
		if(dml){
			upsert contacts;
		}
		return contacts;
	}
	public static Contact factoryContact(Boolean dml, Account account, String name){
		Contact contact = new Contact();
		if(account == null){
			account = factoryAccount(true);
		}
		// Name manager
        List<String> nameList = nameGenerator(name);
        contact.FirstName = nameList.get(1);
        contact.LastName = nameList.get(2);
        contact.AccountId = account.Id;
		if(dml){
			upsert contact;
		}
        return contact;
	}

	public static List<String> nameGenerator(String name){
		List<String> nameList = new List<String>();
		if(String.isBlank(name)){
			nameList.add('Test Name');
	        nameList.add('Test');
	        nameList.add('Name');
		}
		else {
			nameList.add(name);
			Integer spaceIndex = name.indexOf(' ');
			if(spaceIndex > 0){
	        	nameList.add(name.left(spaceIndex));
				nameList.add(name.right(name.length() - (spaceIndex + 1)));
			}
			else {
				nameList.add('Test');
				nameList.add(name);
			}
		}
		return nameList;
	}
	
}