src/objects/Environment__c.object
<CustomObject>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <label>Branch Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CI_Project_Definition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CI Project Definition</label>
        <referenceTo>ProjectDefinition__c</referenceTo>
        <relationshipLabel>Environments</relationshipLabel>
        <relationshipName>Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Environment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Environment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose an Enviroment that is a member of the same Project Definition</errorMessage>
            <filterItems>
                <field>Environment__c.CI_Project_Definition__c</field>
                <operation>equals</operation>
                <valueField>$Source.CI_Project_Definition__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Environment__c</referenceTo>
        <relationshipLabel>Environments</relationshipLabel>
        <relationshipName>Child_Environments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Production</label>
        <type>Checkbox</type>
    </fields>
    <label>Environment</label>
    <nameField>
        <label>Environment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ProjectDefinition__c.object
<CustomObject>
    <description>Container for Praying Mantis CI definition</description>
    <fields>
        <fullName>Repo_Name__c</fullName>
        <label>Repository Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CI Project Definition</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CI Project Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EnvironmentTriggerTest.cls
@isTest
public with sharing class EnvironmentTriggerTest {
    public static testMethod void environment_insert_test() {
        String getRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
        String createRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
        Test.setMock(HttpCalloutMock.class, new GithubCalloutMock(createRefBody,getRefBody));

        test.startTest();
            ProjectDefinition__c pd = new ProjectDefinition__c(Name='test', Repo_Name__c='CodeScience/test');
            insert pd ;

            // insert one at a time to run the createUserBranch method
            Environment__c parentEnv = new Environment__c(CI_Project_Definition__c=pd.Id, Name='Production', Production__c=true, Branch_Name__c='master');
            insert parentEnv;
            Environment__c env = new Environment__c(Name='test', CI_Project_Definition__c=pd.Id, Parent_Environment__c=parentEnv.Id, Branch_Name__c='test');
            insert env;
        test.stopTest();
    }

    public static testMethod void environment_insert_no_branch_test() {
        String getRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
        String createRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
        Test.setMock(HttpCalloutMock.class, new GithubCalloutMock(createRefBody,getRefBody));

        Test.startTest();
            ProjectDefinition__c pd = new ProjectDefinition__c(Name='test', Repo_Name__c='CodeScience/test');
            insert pd ;

            // insert one at a time to run the createUserBranch method
            Environment__c parentEnv = new Environment__c(CI_Project_Definition__c=pd.Id, Name='Production', Production__c=true, Branch_Name__c='master');
            insert parentEnv;
            Environment__c env = new Environment__c(Name='test', CI_Project_Definition__c=pd.Id, Parent_Environment__c=parentEnv.Id);
            
            try{
                insert env;
            } catch(GithubService.CustomException e) {
                system.assertEquals('The environment either does not exist or does not contain a parent or a branch name', e.getMessage());
            }
        Test.stopTest();
    }

    public static testMethod void environment_insert_no_repo_test() {
        String getRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
        String createRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
        Test.setMock(HttpCalloutMock.class, new GithubCalloutMock(createRefBody,getRefBody));

        Test.startTest();
            ProjectDefinition__c pd = new ProjectDefinition__c(Name='test');
            insert pd ;

            // insert one at a time to run the createUserBranch method
            Environment__c parentEnv = new Environment__c(CI_Project_Definition__c=pd.Id, Name='Production', Production__c=true, Branch_Name__c='master');
            insert parentEnv;
            Environment__c env = new Environment__c(Name='test', CI_Project_Definition__c=pd.Id, Parent_Environment__c=parentEnv.Id, Branch_Name__c='test');
            
            try{
                insert env;
            } catch(GithubService.CustomException e) {
                system.assertEquals('The CI Project Definition is missing one or more required fields', e.getMessage());
            }
        Test.stopTest();
    }

    public static testMethod void environment_insert_no_parent_branch_test() {
            String getRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
            String createRefBody = '{"ref": "refs/heads/featureA","url": "https://api.github.com/repos/octocat/Hello-World/git/refs/heads/featureA","object": {"type": "commit","sha": "aa218f56b14c9653891f9e74264a383fa43fefbd","url": "https://api.github.com/repos/octocat/Hello-World/git/commits/aa218f56b14c9653891f9e74264a383fa43fefbd"}}';
            Test.setMock(HttpCalloutMock.class, new GithubCalloutMock(createRefBody,getRefBody));
            
            Test.startTest();
            ProjectDefinition__c pd = new ProjectDefinition__c(Name='test', Repo_Name__c='CodeScience/test');
            insert pd ;

            // insert one at a time to run the createUserBranch method
            Environment__c parentEnv = new Environment__c(CI_Project_Definition__c=pd.Id, Name='Production', Production__c=true);
            insert parentEnv;
            Environment__c env = new Environment__c(Name='test', CI_Project_Definition__c=pd.Id, Parent_Environment__c=parentEnv.Id, Branch_Name__c='test');
            
            try{
                insert env;
            } catch(GithubService.CustomException e) {
                system.assertEquals('The CI Project Definition is missing one or more required fields', e.getMessage());
            }
        Test.stopTest();
    }
}