src/objects/Qualtrics_API_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>used to store each user&apos;s Qualtrics settings for API calls</description>
    <fields>
        <fullName>API_Token__c</fullName>
        <label>API Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualtrics API Settings</label>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit Response Mappings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_ID__c</fullName>
        <description>The id used to identify this survey in Qualtrics.</description>
        <externalId>true</externalId>
        <label>Survey ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>QS-{000}</displayFormat>
        <label>Qualtrics Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QualtricsCanvasController.cls
public with sharing class QualtricsCanvasController {

	public final Survey__c survey {get;set;}
	private final ApexPages.StandardController stdCtrl {get;set;}
    private Boolean hasQualtricsAdminPermission;
	public Boolean showSurveyDetail {get;set;}
	public Boolean showCanvas {get;set;}
	public Map<String,String> requestParamMap {get;set;}
	public String requestParamJSON {get;set;}

	public QualtricsCanvasController(ApexPages.StandardController stdController) {
		setHasQualtricsAdminPermission();
		this.stdCtrl = stdController;
		this.showSurveyDetail = false;
		this.showCanvas = false;
		this.survey = [SELECT Id, Name, Survey_ID__c, Status__c FROM Survey__c WHERE Id = :stdController.getId() LIMIT 1];
	}

    private void setHasQualtricsAdminPermission() {
        CustomPermissionsReader cpr = new CustomPermissionsReader(Survey__c.sObjectType);
        hasQualtricsAdminPermission = cpr.hasPermission('Qualtrics_Admin');
    }

	public PageReference routeSurvey() {
		PageReference routePage;
		if(survey.Id != null){
			if(survey.Status__c == 'Panel Created' || survey.Status__c == 'Edit Survey' || survey.Status__c == 'Edit Response Mappings'){
	        	routePage = new PageReference('/apex/SelectSurvey?surveyid='+survey.Id);
	        	routePage.setRedirect(true);
	        }
	        else if(survey.Status__c == 'Message'){
	        	routePage = new PageReference('/apex/SurveyMessage?surveyid='+survey.Id);
	        	routePage.setRedirect(true);
	        }
	        else{
	        	showSurveyDetail = true;
	        	renderCanvas(survey.Survey_ID__c,null);
	        	routePage = null;
	        }
		}
        else {
        	ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error: No valid Survey Id.');
            ApexPages.addMessage(myMsg);
        }
        return routePage;
    }

    public void renderCanvas(String surveyId, String section){
		requestParamMap = new Map<String,String>();
		requestParamMap.put('qualtricsUserToken',Qualtrics_API_Settings__c.getInstance(UserInfo.getUserId()).API_Token__c);
		requestParamMap.put('surveyId',surveyId);
		if(section != null){
			requestParamMap.put('section', section);
		}
		requestParamJSON = JSON.serialize(requestParamMap);
	}
}