src/objects/Qualtrics_API_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>used to store each user&apos;s Qualtrics settings for API calls</description>
    <fields>
        <fullName>Qualtrics_Is_Connected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Qualtrics Is Connected</label>
        <type>Checkbox</type>
    </fields>
    <label>Qualtrics API Settings</label>
</CustomObject>

src/classes/QualtricsRestSvc.cls
/****************************************************************************************
Name            : QualtricsRestSvc
Revision Log    : 2016-02-11 Steve Swiger - CodeScience
                : 
                : 
Use             : This class handles request from Qualtrics to update the 
                : Qualtrics_Is_Connected__c flag in the Qualtrics_API_Settings__c
                : custom setting
****************************************************************************************/
@RestResource(urlMapping='/Qualtrics/*')
global with sharing class QualtricsRestSvc
{
    @HttpPost
    global static String connectionUpdater(Integer isConnected) {
    	try {
	    	Qualtrics_API_Settings__c qSettings = Qualtrics_API_Settings__c.getInstance(UserInfo.getUserId());
	    	if(isConnected == 1){
	    		qSettings.Qualtrics_Is_Connected__c = true;
	    	}
	    	else {
	    		qSettings.Qualtrics_Is_Connected__c = false;
	    	}
	    	update qSettings;
	        return 'Success';
	    }
	    catch(exception ex) {
	    	System.debug('An Error Occurred: QualtricsService.connectionUpdater(' + ex.getLineNumber() + ') - ' + ex.getMessage());
	    	return 'Failure : An Error Occurred: QualtricsService.connectionUpdater(' + ex.getLineNumber() + ') - ' + ex.getMessage();
	    }
    }
}