src/objects/Qualtrics_API_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>used to store each user&apos;s Qualtrics settings for API calls</description>
    <fields>
        <fullName>API_Token__c</fullName>
        <label>API Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Qualtrics API Settings</label>
</CustomObject>

src/objects/Qualtrics_Email_Opt_out__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores SObject Name and Field Names to be used for email Opt-out values (CHECKBOX ONLY)</description>
    <label>Qualtrics Email Opt-out</label>
</CustomObject>

src/objects/Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>QS-{000}</displayFormat>
        <label>Qualtrics Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Utils.cls
public with sharing class Utils {

	public static Boolean isValidId(String s) {
		Id validId;
		try {
			validId = s;
			return true;
		} catch (Exception ex) {
			return false;
		}
	}

	public static Boolean userHasQualtricsSettings(String userId){
		Qualtrics_API_Settings__c settings = Qualtrics_API_Settings__c.getInstance(userId);
		if(settings.API_Token__c == null){
			return false;
		}		
		return true;
	}

	public static void sendDebugEmail(List<String> toAddresses, String objectInfo){
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			mail.setToAddresses(toAddresses);
			mail.setSubject('Error in qualtrics app');
			mail.setPlainTextBody(objectInfo);
		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });	
	}

	public static void clearEmailOptOutSettingForMissingField() {
        Set<Id> missingEmailOptOutFields = PanelMember.checkMissingOptOutFields();
        if(missingEmailOptOutFields.size() > 0) {
            List<Qualtrics_Email_Opt_out__c> deleteSettings = new List<Qualtrics_Email_Opt_out__c>();
            for(Id del : missingEmailOptOutFields) {
                deleteSettings.add(new Qualtrics_Email_Opt_out__c(Id=del));
            }
            delete deleteSettings;
        }
	}

	public static Boolean userHasQualtricsAdminPermission() {
        CustomPermissionsReader cpr = new CustomPermissionsReader(Survey__c.sObjectType);
        return cpr.hasPermission('Qualtrics_Admin');
    }

    public static string generateBase64UniqueString(String incomingString) {
    	if(!string.isBlank(incomingString)) {
			Blob targetBlob = Blob.valueOf(incomingString);
			Blob hashSHA1 = Crypto.generateDigest('SHA1', targetBlob);
			String hashBase64SHA1 = EncodingUtil.base64encode (hashSHA1);
			return hashBase64SHA1;
		}
		return '';
    }

}