src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Email_Missing__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Qualtrics filters records with no email address</inlineHelpText>
        <label># Email Missing</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email_Opt_Out__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Qualtrics filters records based on email opt-out rules set by your Salesforce admin</inlineHelpText>
        <label># Email Opt Out</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Panel_ID__c</fullName>
        <description>The id used to identify the panel created for this survey in Qualtrics.</description>
        <externalId>true</externalId>
        <label>Panel ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sent__c</fullName>
        <label># in List</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>QS-{000}</displayFormat>
        <label>Qualtrics Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Survey_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Survey Campaigns</relationshipLabel>
        <relationshipName>Survey_Campaigns</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SendSurveyCompleteTimestamp__c</fullName>
        <label>Send Survey Complete Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Survey Campaigns</relationshipLabel>
        <relationshipName>Survey_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Campaign</label>
    <nameField>
        <displayFormat>QSC-{000}</displayFormat>
        <label>Survey Campaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendSurveyBatch.cls
global class SendSurveyBatch implements Database.Batchable<SObject>, Database.Stateful, Database.AllowsCallouts {
    global Id surveyId;
    global String panelId;
    global Integer validMemberCount;
    global Boolean leadOptOutAccessible;
    global Boolean contactOptOutAccessible;
    global Map<String,Boolean> leadOptOutsAccessible;
    global Map<String,Boolean> contactOptOutsAccessible;
    global Integer recordsTotal {get;set;}
    global Integer recordsNullEmail {get;set;}
    global Integer recordsOptOut {get;set;}
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        validMemberCount = 0;
        recordsTotal = 0;
        recordsNullEmail = 0;
        recordsOptOut = 0;
        Set<String> leadAccFields = PanelMember.leadAccessibleFields;
        leadOptOutsAccessible = new Map<String,Boolean>();
        for(String field : PanelMember.leadOptOutFieldSet) {
            leadOptOutsAccessible.put(field,PanelMember.leadAccessibleFields.contains(field) ? true : false);
        }

        Set<String> lContactAccFields = PanelMember.contactAccessibleFields;
        contactOptOutsAccessible = new Map<String,Boolean>();
        for(String field : PanelMember.contactOptOutFieldSet) {
            contactOptOutsAccessible.put(field,PanelMember.contactAccessibleFields.contains(field) ? true : false);
        }

        Utils.clearEmailOptOutSettingForMissingField();

        return Database.getQueryLocator(
            [SELECT Id, LeadId, ContactId, CampaignId
               FROM CampaignMember
              WHERE CampaignId IN (SELECT Campaign__c
                                     FROM Survey_Campaign__c
                                    WHERE Survey__c = :this.surveyId)]);
    }
    
    global void execute(Database.BatchableContext BC, List<CampaignMember> cms) {
        List<CampaignMember> members = Database.query(getCampaignMemberQuery());
        List<String> memberStrings = new List<String>();
        for (CampaignMember cm : members) {
            String campaignId = cm.Id;
            Campaign c = cm.Campaign;
            
            if (cm.Lead != null) {
                if(!String.isBlank(cm.Lead.Email)){
                    boolean optOutAccessible = false;
                    boolean optedOut = false;
                    for(String field : leadOptOutsAccessible.keySet()) {
                        if(leadOptOutsAccessible.get(field) == true) {
                            optOutAccessible = true;
                            if(cm.Lead.get(field) == true) {
                                optedOut = true;
                                break;
                            }
                        }
                    }
                    if(!optOutAccessible || (optOutAccessible && !optedOut)) {
                        memberStrings.add(PanelMember.makeMemberString(cm.Lead, c, surveyId));
                    }
                    else {
                        recordsOptOut += 1;
                    }
                }
                else {
                    recordsNullEmail += 1;
                }
                recordsTotal += 1;
            } 
            else if (cm.Contact != null) {
                if(!String.isBlank(cm.Contact.Email)){
                    boolean optOutAccessible = false;
                    boolean optedOut = false;
                    for(String field : contactOptOutsAccessible.keySet()) {
                        if(contactOptOutsAccessible.get(field) == true) {
                            optOutAccessible = true;
                            if(cm.Contact.get(field) == true) {
                                optedOut = true;
                                break;
                            }
                        }
                    }
                    if(!optOutAccessible || (optOutAccessible && !optedOut)) {
                        memberStrings.add(PanelMember.makeMemberString(cm.Contact, c, surveyId));
                    }
                    else {
                        recordsOptOut += 1;
                    }
                }
                else {
                    recordsNullEmail += 1;
                }
                recordsTotal += 1;
            }
        }
        QualtricsAPI.addPanelMembers(this.panelId, memberStrings);
    }
    
    global void finish(Database.BatchableContext BC) {
        this.validMemberCount = this.recordsTotal - (this.recordsNullEmail + this.recordsOptOut);
        // Update the Panel Member count on the Survey
        if(this.validMemberCount > 0){
            Survey__c survey = [SELECT Id, Sent__c FROM Survey__c WHERE Id = :this.surveyId LIMIT 1];
            survey.Sent__c = this.validMemberCount;
            survey.Email_Missing__c = this.recordsNullEmail;
            survey.Email_Opt_Out__c = this.recordsOptOut;
            update survey;
        }
        
        // Update the survey as sent
        List<Survey_Campaign__c> scs = [SELECT Id, SendSurveyCompleteTimestamp__c
                                          FROM Survey_Campaign__c
                                         WHERE Survey__c = :this.surveyId];
        for (Survey_Campaign__c sc : scs) {
            sc.SendSurveyCompleteTimestamp__c 	= DateTime.now();
        }
        update scs;
        
        // See if other surveys need to be processed
        List<Survey__c> surveys = [SELECT Id, Panel_ID__c
                                     FROM Survey__c
                                    WHERE Id IN (SELECT Survey__c
                                                   FROM Survey_Campaign__c
                                                  WHERE SendSurveyCompleteTimestamp__c = null)
                                    LIMIT 1];
        if (surveys.size() > 0) {
            // Another job needs to be submitted
            submitBatchJob(surveys.get(0).Id, surveys.get(0).Panel_ID__c);
        }
    }
    
    /**
     * This method should be called by any other process that needs to submit this batch job.
     */
    public static Id submitBatchJob(Id surveyId, String panelId) {
        Id returnValue = null;
        
        // See if any other Apex Batch Jobs have been queued
        List<String> statuses = new List<String>{'Queued', 'Processing', 'Preparing'};
            List<AsyncApexJob> jobs = [SELECT Id
                                       FROM AsyncApexJob
                                       WHERE ApexClass.Name = 'SendSurveyBatch'
                                       AND Status IN :statuses];
        if (jobs.size() == 0) {
            // No other batch jobs are in the queue, let's add one
            try {
                SendSurveyBatch ssb	= new SendSurveyBatch();
                ssb.surveyId	= surveyId;
                ssb.panelId		= panelId;
                
                returnValue = Database.executeBatch(ssb, 2000);
            } catch (Exception e) {
                System.debug(e);
            }
        }
        
        return returnValue;
    }
    
    // split this out so that it's easier to test
    public static String getCampaignMemberQuery() {
        return 'SELECT Id, CampaignId, Contact.Account.Name, Contact.' +
            String.join(new List<String>(PanelMember.contactAccessibleFields), ', Contact.') + ', Lead.' +
            String.join(new List<String>(PanelMember.leadAccessibleFields), ', Lead.') + ', Campaign.' +
            String.join(new List<String>(PanelMember.campaignAccessibleFields), ', Campaign.') + 
            ' FROM CampaignMember WHERE Id IN :cms';
    }
}