src/objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Message_ID__c</fullName>
        <description>The Qualtrics id of the message created for this survey, or the id of an existing Qualtrics message selected to be used with this survey.</description>
        <externalId>true</externalId>
        <label>Message ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Panel_ID__c</fullName>
        <description>The id used to identify the panel created for this survey in Qualtrics.</description>
        <externalId>true</externalId>
        <label>Panel ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Panel Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit Response Mappings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Message</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Survey_ID__c</fullName>
        <description>The id used to identify this survey in Qualtrics.</description>
        <externalId>true</externalId>
        <label>Survey ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>QS-{000}</displayFormat>
        <label>Qualtrics Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QualtricsCanvasController_Test.cls
@isTest
private class QualtricsCanvasController_Test
{
	@isTest
	static void itShould_testPanelCreatedJump()
	{
		// Given
		User user = TestingUtils.createTestUser();
		TestingUtils.createApiCustomSettings(user);
  		
		// When
		System.runAs(user) {
			Survey__c survey = new Survey__c();
			survey.Survey_ID__c = 'test';
			survey.Panel_ID__c = 'test';
			survey.Message_ID__c = 'test';
			survey.Status__c = 'Panel Created';
			insert survey;

			Test.startTest();
			ApexPages.StandardController sc = new ApexPages.StandardController(survey);
			QualtricsCanvasController controller = new QualtricsCanvasController(sc);
			String nextPage = controller.routeSurvey().getUrl();
			survey = [SELECT Id, Name, Survey_ID__c, Status__c FROM Survey__c WHERE Id = :sc.getId() LIMIT 1];
			//System.assertEquals('/apex/qualtrics__SelectSurvey?surveyid='+survey.Id, nextPage);
			System.assert(nextPage.contains('SelectSurvey?surveyid='+survey.Id));
			Test.stopTest();
		}
	}

	@isTest
	static void itShould_testAdminSurveyDetailJump()
	{
		// Given
		User user = TestingUtils.createAdminUserWithAdminPermSet();
  		
		// When
		System.runAs(user) {
			TestingUtils.createApiCustomSettings(user);
			Survey__c survey = new Survey__c();
			survey.Survey_ID__c = 'test';
			survey.Panel_ID__c = 'test';
			survey.Message_ID__c = 'test';
			survey.Status__c = 'Survey Detail';
			insert survey;

			Test.startTest();
			ApexPages.StandardController sc = new ApexPages.StandardController(survey);
			QualtricsCanvasController controller = new QualtricsCanvasController(sc);
			PageReference nextPage = controller.routeSurvey();
			survey = [SELECT Id, Name, Survey_ID__c, Status__c FROM Survey__c WHERE Id = :sc.getId() LIMIT 1];
			//System.assertEquals('/apex/qualtrics__SelectSurvey?surveyid='+survey.Id, nextPage);
			System.assert(nextPage == null);
			Test.stopTest();
		}
	}

	@isTest
	static void itShould_testSendMessageJump()
	{
		// Given
		User user = TestingUtils.createTestUser();
		TestingUtils.createApiCustomSettings(user);
  		
		// When
		System.runAs(user) {
			Survey__c survey = new Survey__c();
			survey.Survey_ID__c = 'test';
			survey.Panel_ID__c = 'test';
			survey.Message_ID__c = 'test';
			survey.Status__c = 'Message';
			insert survey;

			Test.startTest();
			ApexPages.StandardController sc = new ApexPages.StandardController(survey);
			QualtricsCanvasController controller = new QualtricsCanvasController(sc);
			String nextPage = controller.routeSurvey().getUrl();
			survey = [SELECT Id, Name, Survey_ID__c, Status__c FROM Survey__c WHERE Id = :sc.getId() LIMIT 1];
			//System.assertEquals('/apex/qualtrics__SurveyMessage?surveyid='+survey.Id, nextPage);
			System.assert(nextPage.contains('SurveyMessage?surveyid='+survey.Id));
			Test.stopTest();
		}
	}

	@isTest
	static void itShould_renderCanvas()
	{
		// Given
		User user = TestingUtils.createTestUser();
		TestingUtils.createApiCustomSettings(user);
  		
		// When
		System.runAs(user) {
			Survey__c survey = new Survey__c();
			survey.Survey_ID__c = 'test';
			survey.Panel_ID__c = 'test';
			survey.Message_ID__c = 'test';
			survey.Status__c = 'Message';
			insert survey;

			Test.startTest();
			ApexPages.StandardController sc = new ApexPages.StandardController(survey);
			QualtricsCanvasController controller = new QualtricsCanvasController(sc);
			controller.renderCanvas(survey.Id,null);
			Test.stopTest();
		}
	}
}